services:
  sup1:
    container_name: sup1
    image: dockersup
    networks:
     - vpcbr

  sup2:
    container_name: sup2
    image: dockersup
    networks:
     - vpcbr

networks:
  vpcbr:
    driver: bridge 
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
         aux_addresses:
          mysql: 10.5.0.5
          apigw-tomcat: 10.5.0.6